version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileFrontendPPA
    container_name: frontendPPA
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Activa polling para asegurar detección de cambios en Docker
    networks:
      - redwebPPA

  backend:
    build:
      context: ./backend
      dockerfile: DockerfileBackendPPA
    container_name: backendPPA
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t public"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - redwebPPA

  web:
    build:
      context: ./web
      dockerfile: DockerfileWebPPA
    container_name: webPPA
    ports:
      - "80:80" # Si tienes problemas con el puerto 80, cambia el puerto externo aquí
    networks:
      - redwebPPA

networks:
  redwebPPA:
    driver: bridge
